default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: ['--wrap=80']
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest-idg
        name: pytest-idg
        stages: [manual] # only run when specified manually
        entry: bash -c 'cd idg/python; uv run --env-file=.env pytest'
        language: system
        types: [python]
        pass_filenames: false
        always_run: false
      - id: build-idg
        name: build-idg
        stages: [manual] # only run when specified manually
        entry: bash -c 'cd idg/python; uv run --env-file=.env -m build'
        language: system
        types: [python]
        pass_filenames: false
        always_run: false
