NR_CORRELATIONS_IN = 2  # XX, YY
NR_CORRELATIONS_OUT = 1  # I
SUBGRID_SIZE = 32  # size of each subgrid
GRID_SIZE = 1024  # size of the full grid
OBSERVATION_HOURS = 4  # total observation time in hours
NR_TIMESTEPS = OBSERVATION_HOURS * 3600
NR_CHANNELS = 16  # number of frequency channels
W_STEP = 1.0  # w step in wavelengths

START_FREQUENCY = 150e6  # 150 MHz
FREQUENCY_INCREMENT = 1e6  # 1 MHz
END_FREQUENCY = START_FREQUENCY + NR_CHANNELS * FREQUENCY_INCREMENT

SPEED_OF_LIGHT = 299792458.0
IMAGE_SIZE = SPEED_OF_LIGHT / END_FREQUENCY

NR_STATIONS = 20
NR_BASELINES = NR_STATIONS * (NR_STATIONS - 1) // 2
