on:
  pull_request:
  push:
    branches: main
jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: idg/python
            adapter: python_pytest
            args: --file results.json
            cmd: uv run pytest --benchmark-only --benchmark-json=results.json
          - project: idg/rust
            adapter: rust_criterion
            cmd: cargo bench
    steps:
      - uses: actions/checkout@v6
      - uses: bencherdev/bencher@main
      - uses: astral-sh/setup-uv@v7
        if: matrix.adapter == 'python_pytest'
      - name: Track benchmarks with Bencher
        working-directory: ${{ matrix.project }}
        run: |
          bencher run \
          --project astron-pace \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --error-on-alert \
          --adapter ${{ matrix.adapter }} \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          ${{ matrix.args }} "${{ matrix.cmd }}"
