on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  benchmark:
    # DO NOT REMOVE: Block GitHub actions for Fork PRs
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application: [idg]
        experiment:
          - branch: python
            adapter: python_pytest
            command: --file results.json "uv run pytest --benchmark-only --benchmark-json=results.json"
          - branch: rust
            adapter: rust_criterion
            command: "cargo bench"
    steps:
      - uses: actions/checkout@v6
      - uses: bencherdev/bencher@main
      - uses: astral-sh/setup-uv@v7
        if: matrix.experiment.adapter == 'python_pytest'
      - name: Run benchmarks with Bencher
        working-directory: ${{ matrix.application }}/${{ matrix.experiment.branch }}
        run: |
          bencher run \
          --project astron-pace \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch ${{ matrix.experiment.branch }} \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --error-on-alert \
          --adapter ${{ matrix.experiment.adapter }} \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          ${{ matrix.experiment.command }}
