on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  benchmark:
    # DO NOT REMOVE: Block GitHub actions for Fork PRs
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: idg/python
            adapter: python_pytest
            args: --file results.json
            cmd: uv run pytest --benchmark-only --benchmark-json=results.json
          - dir: idg/rust
            adapter: rust_criterion
            cmd: cargo bench
    steps:
      - uses: actions/checkout@v6
      - uses: bencherdev/bencher@main
      - uses: astral-sh/setup-uv@v7
        if: matrix.adapter == 'python_pytest'
      - name: Track base branch benchmarks with Bencher
        if: github.event_name == 'push'
        working-directory: ${{ matrix.dir }}
        run: |
          bencher run \
          --project astron-pace \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --error-on-alert \
          --adapter ${{ matrix.adapter }} \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          ${{ matrix.args }} "${{ matrix.cmd }}"
      - name: Track PR benchmarks with Bencher
        if: github.event_name == 'pull_request'
        working-directory: ${{ matrix.dir }}
        run: |
          bencher run \
          --project astron-pace \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch "$GITHUB_HEAD_REF" \
          --start-point "$GITHUB_BASE_REF" \
          --start-point-hash '${{ github.event.pull_request.base.sha }}' \
          --start-point-clone-thresholds \
          --start-point-reset \
          --testbed ubuntu-latest \
          --error-on-alert \
          --adapter ${{ matrix.adapter }} \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          ${{ matrix.args }} "${{ matrix.cmd }}"
