name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.1.0
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage manual --all
